import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Calculate from './calculate'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p data-testid = "tex">hi</p>
        <Calculate></Calculate>
      </main>
    </div>
  )
}
